#
# ~/.nixos/home/modules/hyprland/hyprlock.nix
#
# Visual style: blurred screenshot + clock + input field.
# Colors come from ~/.config/hypr/hyprlock-colors.conf generated by matugen.
#
{ ... }: {
  programs.hyprlock = {
    enable = true;
    settings = {
      background = [{
        monitor    = "";
        path       = "screenshot";
        blur_passes = 2;
        blur_size  = 8;
        brightness = 0.7;
      }];
    };

    # Source matugen-generated color variables, then define input field and labels.
    # Variables ($inputOutline etc.) are defined in hyprlock-colors.conf.
    extraConfig = ''
      source = ~/.config/hypr/hyprlock-colors.conf

      input-field {
          monitor           =
          size              = 300, 50
          outline_thickness = 2
          dots_size         = 0.26
          dots_spacing      = 0.64
          outer_color       = $inputOutline
          inner_color       = $inputBg
          font_color        = $inputFg
          fade_on_empty     = true
          placeholder_text  = <i>Password</i>
          rounding          = 10
          check_color       = $checkColor
          fail_color        = $failColor
          fail_text         = <i>Auth Failed</i>
          capslock_color    = $capslockColor
          position          = 0, -20
          halign            = center
          valign            = center
      }

      label {
          monitor     =
          text        = cmd[update:1000] echo "$(date +'%H:%M')"
          color       = $clockColor
          font_size   = 72
          font_family = Inter
          position    = 0, 200
          halign      = center
          valign      = center
      }

      label {
          monitor     =
          text        = cmd[update:60000] echo "$(date +'%A, %B %-d')"
          color       = $dateColor
          font_size   = 20
          font_family = Inter
          position    = 0, 120
          halign      = center
          valign      = center
      }
    '';
  };
}
