#
# ~/.nixos/home/modules/hyprland/hyprlock.nix
#
# Visual style: blurred wallpaper + clock + input field.
# Colors come from ~/.config/hypr/hyprlock-colors.conf generated by matugen.
#
# path = "screenshot" is intentionally avoided — on NVIDIA (RTX 3080 Ti) the
# wlr-screencopy call races with hyprlock's session-lock surface acquisition,
# causing hyprlock to crash before it acquires the lock. Using the wallpaper
# file directly sidesteps the screencopy path entirely.
#
{ ... }: {
  programs.hyprlock = {
    enable = true;
    settings = {
      background = [{
        monitor    = "";
        path       = "$HOME/.config/background";
        blur_passes = 2;
        blur_size  = 8;
        # 0.7 only worked for bright wallpapers. The text is light now (see the
        # hyprlock template in matugen.nix), so the backdrop has to be dark for
        # every wallpaper, not just the dark ones: against a white wallpaper
        # 0.7 leaves 1.64:1 and 0.4 leaves 4.45:1, while a dark wallpaper is far
        # above either. Drop to 0.35 if a future wallpaper still reads washed
        # out — that is 5.43:1 at the cost of showing less of the picture.
        brightness = 0.4;
      }];
    };

    # Source matugen-generated color variables, then define input field and labels.
    # Variables ($inputOutline etc.) are defined in hyprlock-colors.conf.
    extraConfig = ''
      source = ~/.config/hypr/hyprlock-colors.conf

      input-field {
          monitor           =
          size              = 300, 50
          outline_thickness = 2
          dots_size         = 0.26
          dots_spacing      = 0.64
          outer_color       = $inputOutline
          inner_color       = $inputBg
          font_color        = $inputFg
          fade_on_empty     = true
          placeholder_text  = <i>Password</i>
          rounding          = 10
          check_color       = $checkColor
          fail_color        = $failColor
          fail_text         = <i>Auth Failed</i>
          capslock_color    = $capslockColor
          position          = 0, -20
          halign            = center
          valign            = center
      }

      label {
          monitor     =
          text        = cmd[update:1000] echo "$(date +'%H:%M')"
          color       = $clockColor
          # Contrast against a *photo* is an average, not a guarantee: a pale
          # blurred highlight under the glyphs beats any single colour choice.
          # The shadow costs nothing on a dark backdrop and rescues that case.
          shadow_passes = 2
          shadow_size   = 3
          shadow_color  = rgba(00000099)
          font_size   = 72
          font_family = Inter
          position    = 0, 200
          halign      = center
          valign      = center
      }

      label {
          monitor     =
          text        = cmd[update:60000] echo "$(date +'%A, %B %-d')"
          color       = $dateColor
          shadow_passes = 2
          shadow_size   = 3
          shadow_color  = rgba(00000099)
          font_size   = 20
          font_family = Inter
          position    = 0, 120
          halign      = center
          valign      = center
      }
    '';
  };
}
