#
# ~/.nixos/home/modules/alacritty.nix
#
{pkgs, ...}: {
  programs.alacritty = {
    enable = true;

    settings = {
      window = {
        padding = { x = 16; y = 14; };
        opacity = 0.88;
        blur = true;
        decorations = "None";         # no title bar — Niri handles window chrome
        dynamic_title = true;
      };

      font = {
        normal = { family = "JetBrainsMono Nerd Font"; style = "Regular"; };
        bold   = { family = "JetBrainsMono Nerd Font"; style = "Bold"; };
        italic = { family = "JetBrainsMono Nerd Font"; style = "Italic"; };
        size = 12.0;
        offset = { x = 0; y = 2; };       # slight extra line spacing
        builtin_box_drawing = true;
      };

      cursor = {
        style = { shape = "Block"; blinking = "On"; };
        blink_interval = 500;
        unfocused_hollow = true;
      };

      scrolling = {
        history = 10000;
        multiplier = 3;
      };

      # Colors are generated by matugen into ~/.config/alacritty/colors.toml
      general.import = [ "~/.config/alacritty/colors.toml" ];

      terminal.shell = {
        program = "${pkgs.zsh}/bin/zsh";
      };
    };
  };
}
