#
# ~/.nixos/home/modules/fuzzel.nix
#
# fuzzel — Wayland-native app launcher (SUPER+SPACE in the Hyprland session).
# Full fuzzel.ini (including [colors]) is generated by matugen — see matugen.nix.
#
{ pkgs, ... }: {
  home.packages = [ pkgs.fuzzel ];
}
