# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["xhci_pci" "nvme" "ahci" "usb_storage" "sd_mod"];
      kernelModules = [];
    };

    kernelModules = ["kvm-amd" "nvidia"];
    extraModulePackages = [];
    kernelParams = ["quiet" "splash" "loglevel=0"];
    consoleLogLevel = 0;
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/702432b6-78d0-4991-a8f1-a36ae055b15b";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/79D0-EA35";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/beea1832-8a4b-4946-8baf-27175b2f5ac8";
    fsType = "ext4";
  };

  #fileSystems."/var/lib/ollama" = {
  #  device = "/dev/disk/by-uuid/beea1832-8a4b-4946-8baf-27175b2f5ac8";
  #  fsType = "ext4";
  #};
  swapDevices = [
    {device = "/dev/disk/by-uuid/2d923b45-51be-436f-96eb-6467d945d2d1";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
